### PR TITLE
Fix #89 by ignoring only keys which are actually used in Pillar 'postfix:mapping'

### LINKED ISSUE #89: virtual_alias_maps parameter is ignored.
I am trying to configure the virtual_alias_maps parameter against two maps in my pillar data. In #83, it was suggested something like this might be possible in the future:
```
postfix:
  config:
    virtual_alias_maps:
      - hash:/etc/postfix/virtual
      - pcre:/etc/postfix/virtual.pcre
  mapping:
    hash:/etc/postfix/virtual:
      root:
        - me
    pcre:/etc/postfix/virtual.pcre:
      - '/(\S+)_(devel|preprod|prod)@sub.example.com$/': '$(1)@$(2).sub.example.com' 
```

But that isn't supported yet, so I was trying to do this instead:
```
postfix:
  config:
    virtual_alias_maps: $virtual_alias_1_maps $virtual_alias_2_maps
    virtual_alias_1_maps: hash:/etc/postfix/virtual
    virtual_alias_2_maps: pcre:/etc/postfix/virtual.pcre
  mapping:
    virtual_alias_1_maps:
      root:
        - me
    virtual_alias_2_maps:
      - '/(\S+)_(devel|preprod|prod)@sub.example.com$/': '$(1)@$(2).sub.example.com' 
```

The two files /etc/postfix/virtual and /etc/postfix/virtual.pcre get created, however, no parameter entry is added for virtual_alias_maps!

### PR DESCRIPTION
**Pull request by alxwr**
With this change the following becomes feasible:

```yaml
postfix:
  config:
    virtual_alias_maps: "$my_va_map"
    my_va_map: hash:{{ pillar['userland_etc'] }}/postfix/virtual_alias_maps
  mapping:
    # previously: 'virtual_alias_maps:'
    my_va_map:
      - '@example.test': catchall@example.test
```

resulting in

```yaml
----------                                                                                                
          ID: /usr/local/etc/postfix/main.cf                                                              
    Function: file.managed                                                                                
      Result: True                                                                                        
     Comment: File /usr/local/etc/postfix/main.cf updated                                                 
     Started: 20:22:32.857905                                                                             
    Duration: 157.56 ms                                                                                   
     Changes:                                                                                             
              ----------                                                                                  
              diff:                                                                                       
                  ---                                                                                     
                  +++                                                                                     
                  @@ -70,7 +70,7 @@                                                                       
                                                                                                          
                                                                                                          
                                                                                                          
                  -virtual_alias_maps = hash:/usr/local/etc/postfix/virtual_alias_maps
                  +my_va_map = hash:/usr/local/etc/postfix/virtual_alias_maps
                   
                   
                   tls_high_cipherlist = EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA256:EECDH:+
CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!IDEA:!ECDSA:kEDH
                  @@ -89,6 +89,7 @@
                   smtpd_tls_protocols = !SSLv2, !SSLv3
                   smtpd_tls_session_cache_timeout = 3600s
                   strict_rfc821_envelopes = yes
                  +virtual_alias_maps = $my_va_map
                   virtual_mailbox_maps = 
                   virtual_transport = lmtp:unix:private/dovecot-lmtp
                   virtual_mailbox_domains = dmz.tty1.eu
```

This allows also for multiple maps within `virtual_alias_maps` as mentioned in #89 and https://github.com/saltstack-formulas/postfix-formula/issues/83#issuecomment-463342748 by @roskens.

----

I also fixed `mapping.j2` along the way. It didn't work with Python 3.6.

----

Tested on FreeBSD 11.2.

### CODE REVIEW

File: postfix/files/main.cf [hunk 1]
```diff
@@ -1,17 +1,7 @@
...
-{%- set processed_parameters = [] %}
-{%- else -%}
-{#- TODO: alias_maps probably belongs here, too: #}
-{%- set processed_parameters = [
-        'virtual_alias_maps',
-        'smtp_sasl_password_maps',
-        'sender_canonical_maps',
-    ] %}
-{%- endif -%}
+{%- set processed_parameters = salt['pillar.get']('postfix:mapping', {}).keys() | list %}
```
Comment (vutny) [inline postfix/files/main.cf]: @alxwr I don't think you need additional `list` filter. The `keys()` method will always return a new list.

Comment (alxwr) [reply postfix/files/main.cf]: In Python 3.6 `keys()` returns a `dict_keys` object, so the `list` is mandatory.

Without `| list`:

```
jinja2.exceptions.UndefinedError: 'dict_keys object' has no attribute 'append'
```

As far as I understand it: In Python 3.6 `keys()` of an `OrderedDict` object returns a view (which may change) on the keys of the object.

Comment (vutny) [reply postfix/files/main.cf]: Oh, thanks for pointing me out to Python 3.6 specifics, I wasn't aware of that.

However, still think it looks weird. As I can tell from the code, the `processed_parameters` used only once to verify the key exists. No need for such complexity.
We could avoid making the list at all:
```jinja
{%- set processed_parameters = salt['pillar.get']('postfix:mapping', {}) %}
```
Then update the key instead of appending at line 14:
```jinja
{%- do processed_parameters.update({parameter: value}) %}
```
Finally, at line 130 the `if` statement will work the same way.

File: postfix/files/mapping.j2 [hunk 2]
```diff
@@ -21,6 +21,7 @@
 {%- else %}
 {#- Some settings need order, handle OrderedDict #}
 {% for item in data %}
```
Comment (vutny) [inline postfix/files/mapping.j2]: You can simply unpack data in the `for` loop right away:
```jinja
{% for k, v in data %}
{{ format_value(k, v) }}
{%- endfor -%}
```

Comment (alxwr) [reply postfix/files/mapping.j2]: > You can simply unpack data in the `for` loop right away:

Just tried that. It won't fly in Python 3.6:

```
ValueError: not enough values to unpack (expected 2, got 1)
```

File: postfix/files/main.cf (hunk 1 above)
Comment (alxwr) [reply postfix/files/main.cf]: @vutny Thanks for your suggestions regarding the elegance of the code. I appreciate that.

`processed_parameters` was a list, therefore I kept it that way. In my mind it makes more sense to manage a list of parameter _names_ than to needlessly copy their values. `postfix:mapping`'s contents may be quite large. Therefore I suggest we stick with the list.

I disagree with using a dict instead of a list, but if this is non-negotiable, I'll give way. :-)

File: postfix/files/mapping.j2 (hunk 2 above)
Comment (vutny) [reply postfix/files/mapping.j2]: Yeah, I have mixed the list of dicts with the list of tuples. Your changes definitely looks great.

File: postfix/files/main.cf (hunk 1 above)
Comment (vutny) [reply postfix/files/main.cf]: @alxwr No worries, I would just like to make things here as portable as possible because of two reasons:
* Generally using Python methods directly is undesirable, unless there's no other clear way.
  As we've already learned, different Python version have "smaaaall" differences. And the Jinja code is not really Python, it is a layer on top. So it is better to go with Jinja semantics as much as possible in common situations.
* The most heavy call here is `pillar.get`. It needs to fork minion process, talk to the master via message bus and network layer, receive probably megabytes back, cache it, deserialize and finally return back to the caller.
  Lots of stuff going on under the hood. Comparing to that, storing even a big dict in temporary memory is nothing.

If your concern is that holding the values is unnecessary, we could use [pillar.keys](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.pillar.html#salt.modules.pillar.keys) function! Nothing else need to be changed then.

Comment (alxwr) [reply postfix/files/main.cf]: @vutny Then we're on the same page. :-) Thanks for the thorough explanation!

Why didn't I think of `pillar.keys` in the first place? O.o
Thanks for the review and the suggestion! I updated the PR.

The `| list` is needed because of Py3.6: "jinja2.exceptions.UndefinedError: 'dict_keys object' has no attribute 'append'".

File: postfix/files/main.cf [hunk 3]
```diff
@@ -1,17 +1,7 @@
...
-{%- set processed_parameters = [] %}
-{%- else -%}
-{#- TODO: alias_maps probably belongs here, too: #}
-{%- set processed_parameters = [
-        'virtual_alias_maps',
-        'smtp_sasl_password_maps',
-        'sender_canonical_maps',
-    ] %}
-{%- endif -%}
+{%- set processed_parameters = salt['pillar.keys']('postfix:mapping') | list %}
```
Comment (vutny) [inline postfix/files/main.cf]: @alxwr Would you mind to add a comment stating why we need `list` filter here?
We know, because of Python 3.6, but others would appreciate that greatly. :smiley:

Comment (alxwr) [reply postfix/files/main.cf]: > @alxwr Would you mind to add a comment stating why we need `list` filter here?
> We know, because of Python 3.6, but others would appreciate that greatly. smiley

Added comment. :-)

Comment (vutny) [reply postfix/files/main.cf]: Looks like you also need to prepend the `|default([], true)` filter before the `list`, since if the Pillar does not exist, the renderer returns `KeyError: u'Pillar key not found: postfix:mapping'`.

Comment (alxwr) [reply postfix/files/main.cf]: @vutny good catch! :-) Updated the PR.

Comment (alxwr) [reply postfix/files/main.cf]: @vutny We still get that error even with `|default([], true)`:

`KeyError: 'Pillar key not found: postfix:mapping'`

I'd switch back to

```sls
{%- set processed_parameters = salt['pillar.get']('postfix:mapping', {}).keys() | list %}
```

Comment (vutny) [reply postfix/files/main.cf]: Looks like having `pillar.keys` here is not an option here. The exception is raised on the Salt module level, so the `default` filter is no use. I guess we need to revert back to the `get` method and either continue with dict to avoid `dict_keys object` error, or convert it to a list.

Comment (alxwr) [reply postfix/files/main.cf]: Updated the PR.

Comment (alxwr) [reply postfix/files/main.cf]: I'd stick with the list. After all its usable in Py2.7 and Py3.x without jumping through loops.

**Comment by alxwr** [comment]
@vutny Thanks for making me re-think my code and learn new details. :-)
